<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Access Level Selector</name>
   <tag></tag>
   <elementGuidId>0638aabf-619c-4e23-877f-c4b15d3f110e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[contains(@id,'AccessLevelUserComboBox')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//select[@name = 'ANCQuotesCommon_wt15$block$wtMenu$ANCQuotesCommon_wt6$block$wt17$wtAccessLevelUserComboBox' and @id = 'ANCQuotesCommon_wt15_block_wtMenu_ANCQuotesCommon_wt6_block_wt17_wtAccessLevelUserComboBox' and (text() = '
	Select
	L0
	L1
	L2
	L3
	L4
	L5

' or . = '
	Select
	L0
	L1
	L2
	L3
	L4
	L5

')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ANCQuotesCommon_wt15$block$wtMenu$ANCQuotesCommon_wt6$block$wt17$wtAccessLevelUserComboBox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ANCQuotesCommon_wt15_block_wtMenu_ANCQuotesCommon_wt6_block_wt17_wtAccessLevelUserComboBox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>8</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ThemeGrid_Width5 ThemeGrid_MarginGutter</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>OsAjax(arguments[0] || window.event,'ANCQuotesCommon_wt15_block_wtMenu_ANCQuotesCommon_wt6_block_wt17_wtAccessLevelUserComboBox','ANCQuotesCommon_wt15$block$wtMenu$ANCQuotesCommon_wt6$block$wt17$wtAccessLevelUserComboBox','Change','__OSVSTATE,','');</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>this.onchange();</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	Select
	L0
	L1
	L2
	L3
	L4
	L5

</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ANCQuotesCommon_wt15_block_wtMenu_ANCQuotesCommon_wt6_block_wt17_wtAccessLevelUserComboBox&quot;)</value>
   </webElementProperties>
</WebElementEntity>
