<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Antoher Year</name>
   <tag></tag>
   <elementGuidId>4fec2889-cc3f-4c4f-a07a-b7f9b24c0961</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@name = 'ANCQuotesCommon_wt15$block$wtMainContent$wt7$wtYearsDropDown2' and @id = 'ANCQuotesCommon_wt15_block_wtMainContent_wt7_wtYearsDropDown2' and (text() = '
	2018
	2017
	2016
	2015
	2014
	2013
	2012
	2011
	2010
	2009
	2008
	2007
	2006
	2005
	2004
	2003
	2002
	1900

' or . = '
	2018
	2017
	2016
	2015
	2014
	2013
	2012
	2011
	2010
	2009
	2008
	2007
	2006
	2005
	2004
	2003
	2002
	1900

')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'QuotesSummaryHeaderOptn')]//select[contains(@name,'YearsDropDown')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ANCQuotesCommon_wt15$block$wtMainContent$wt7$wtYearsDropDown2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ANCQuotesCommon_wt15_block_wtMainContent_wt7_wtYearsDropDown2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>52</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ThemeGrid_Width4 ThemeGrid_MarginGutter</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>OsAjax(arguments[0] || window.event,'ANCQuotesCommon_wt15_block_wtMainContent_wt7_wtYearsDropDown2','ANCQuotesCommon_wt15$block$wtMainContent$wt7$wtYearsDropDown2','Change','__OSVSTATE,','');</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>this.onchange();</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	2018
	2017
	2016
	2015
	2014
	2013
	2012
	2011
	2010
	2009
	2008
	2007
	2006
	2005
	2004
	2003
	2002
	1900

</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ANCQuotesCommon_wt15_block_wtMainContent_wt7_wtYearsDropDown2&quot;)</value>
   </webElementProperties>
</WebElementEntity>
