<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Backoffice</name>
   <tag></tag>
   <elementGuidId>9404ff20-703e-483e-a42c-1e295669ffba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(@href,'ANCQuotes_BO')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@id = 'ANCQuotesCommon_wt15_block_wtMenu_ANCQuotesCommon_wt6_block_RichWidgets_wt8_block_wtMenuItem_wt15' and @href = '/ANCQuotes_BO' and (text() = 'Backoffice' or . = 'Backoffice')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ANCQuotesCommon_wt15_block_wtMenu_ANCQuotesCommon_wt6_block_RichWidgets_wt8_block_wtMenuItem_wt15</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ANCQuotes_BO</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Backoffice</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ANCQuotesCommon_wt15_block_wtMenu_ANCQuotesCommon_wt6_block_RichWidgets_wt8_block_wtMenuItem_wt15&quot;)</value>
   </webElementProperties>
</WebElementEntity>
