<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Help</name>
   <tag></tag>
   <elementGuidId>17b29105-798f-4873-baa6-85aeb2c81282</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@id = 'ANCQuotesCommon_wt166_block_wtMenu_ANCQuotesCommon_wt224_block_RichWidgets_wt26_block_wtMenuItem_wtHelpLink' and @href = 'https://qa.leap.schneider-electric.com/ANCQuotesCommon/Help.aspx?(Not.Licensed.For.Production)=' and (text() = 'Help' or . = 'Help')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(@id,'HelpLink')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ANCQuotesCommon_wt166_block_wtMenu_ANCQuotesCommon_wt224_block_RichWidgets_wt26_block_wtMenuItem_wtHelpLink</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>6</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://qa.leap.schneider-electric.com/ANCQuotesCommon/Help.aspx?(Not.Licensed.For.Production)=</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Help</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ANCQuotesCommon_wt166_block_wtMenu_ANCQuotesCommon_wt224_block_RichWidgets_wt26_block_wtMenuItem_wtHelpLink&quot;)</value>
   </webElementProperties>
</WebElementEntity>
