<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Home</name>
   <tag></tag>
   <elementGuidId>ad1c8c7c-ae60-4e42-a956-5b25eb0d4f6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@id = 'ANCQuotesCommon_wt15_block_wtMenu_ANCQuotesCommon_wt6_block_RichWidgets_wt28_block_wtMenuItem_wt31' and @href = '/ANCQuotes/HomePage.aspx' and (text() = 'Home' or . = 'Home')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(@href,'Home')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ANCQuotesCommon_wt15_block_wtMenu_ANCQuotesCommon_wt6_block_RichWidgets_wt28_block_wtMenuItem_wt31</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ANCQuotes/HomePage.aspx</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Home</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ANCQuotesCommon_wt15_block_wtMenu_ANCQuotesCommon_wt6_block_RichWidgets_wt28_block_wtMenuItem_wt31&quot;)</value>
   </webElementProperties>
</WebElementEntity>
