<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Quotes</name>
   <tag></tag>
   <elementGuidId>b7c0259f-a176-493e-b4e4-15d8611f89c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@id = 'ANCQuotesCommon_wt26_block_wtMenu_ANCQuotesCommon_wt122_block_RichWidgets_wt13_block_wtMenuItem_wt10' and @href = '/ANCQuotes/Quotes.aspx' and (text() = 'Quotes' or . = 'Quotes')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(@href,'Quotes.aspx')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ANCQuotesCommon_wt26_block_wtMenu_ANCQuotesCommon_wt122_block_RichWidgets_wt13_block_wtMenuItem_wt10</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ANCQuotes/Quotes.aspx</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Quotes</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ANCQuotesCommon_wt26_block_wtMenu_ANCQuotesCommon_wt122_block_RichWidgets_wt13_block_wtMenuItem_wt10&quot;)</value>
   </webElementProperties>
</WebElementEntity>
