<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Region Drop down</name>
   <tag></tag>
   <elementGuidId>32d3cbdf-de73-46fe-be77-b57e16f5a255</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@name = 'ANCQuotesCommon_wt44$block$wtFiltersContent$WebPatterns_wt36$block$wtColumn1$wt24' and @id = 'ANCQuotesCommon_wt44_block_wtFiltersContent_WebPatterns_wt36_block_wtColumn1_wt24' and (text() = '
	ASEAN
	CHINA
	EMEA
	INDIA
	JAPAN
	LAM
	NAM
	PACIFIC 
	ROA
	RUSSIA 

' or . = '
	ASEAN
	CHINA
	EMEA
	INDIA
	JAPAN
	LAM
	NAM
	PACIFIC 
	ROA
	RUSSIA 

')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[text()='Region']//..//..//select[contains(@id,'wtFiltersContent')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ANCQuotesCommon_wt44$block$wtFiltersContent$WebPatterns_wt36$block$wtColumn1$wt24</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ANCQuotesCommon_wt44_block_wtFiltersContent_WebPatterns_wt36_block_wtColumn1_wt24</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>40</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>OSFillParent</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>OsAjax(arguments[0] || window.event,'ANCQuotesCommon_wt44_block_wtFiltersContent_WebPatterns_wt36_block_wtColumn1_wt24','ANCQuotesCommon_wt44$block$wtFiltersContent$WebPatterns_wt36$block$wtColumn1$wt24','Change','__OSVSTATE,','');</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>this.onchange();</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	ASEAN
	CHINA
	EMEA
	INDIA
	JAPAN
	LAM
	NAM
	PACIFIC 
	ROA
	RUSSIA 

</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ANCQuotesCommon_wt44_block_wtFiltersContent_WebPatterns_wt36_block_wtColumn1_wt24&quot;)</value>
   </webElementProperties>
</WebElementEntity>
