<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Search Text Field</name>
   <tag></tag>
   <elementGuidId>f252df2c-825b-44a3-bbff-b93b8ad6e83b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id,'wtSearch_wrapper')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@name = 'ANCQuotesCommon_wt26$block$wtFiltersContent$WebPatterns_wt165$block$wtColumn1$WebPatterns_wt147$block$wtSearch_wrapper$wtSearchInput' and @type = 'text' and @id = 'ANCQuotesCommon_wt26_block_wtFiltersContent_WebPatterns_wt165_block_wtColumn1_WebPatterns_wt147_block_wtSearch_wrapper_wtSearchInput' and @placeholder = 'Search by Module' and @title = 'Type Module Name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ANCQuotesCommon_wt26$block$wtFiltersContent$WebPatterns_wt165$block$wtColumn1$WebPatterns_wt147$block$wtSearch_wrapper$wtSearchInput</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ANCQuotesCommon_wt26_block_wtFiltersContent_WebPatterns_wt165_block_wtColumn1_WebPatterns_wt147_block_wtSearch_wrapper_wtSearchInput</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>36</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>OSFillParent</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search by Module</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return OsEnterKey('ANCQuotesCommon_wt26_block_wtMainContent_wt164', arguments[0] || window.event)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Type Module Name</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onoschange</name>
      <type>Main</type>
      <value>OsAjaxDelayed(null,'ANCQuotesCommon_wt26_block_wtFiltersContent_WebPatterns_wt165_block_wtColumn1_WebPatterns_wt147_block_wtSearch_wrapper_wtSearchInput','ANCQuotesCommon_wt26$block$wtFiltersContent$WebPatterns_wt165$block$wtColumn1$WebPatterns_wt147$block$wtSearch_wrapper$wtSearchInput','Change','__OSVSTATE,',osOnChangeTimerDelay);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>OsAjaxDelayed(null,'ANCQuotesCommon_wt26_block_wtFiltersContent_WebPatterns_wt165_block_wtColumn1_WebPatterns_wt147_block_wtSearch_wrapper_wtSearchInput','ANCQuotesCommon_wt26$block$wtFiltersContent$WebPatterns_wt165$block$wtColumn1$WebPatterns_wt147$block$wtSearch_wrapper$wtSearchInput','Change','__OSVSTATE,',0);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ANCQuotesCommon_wt26_block_wtFiltersContent_WebPatterns_wt165_block_wtColumn1_WebPatterns_wt147_block_wtSearch_wrapper_wtSearchInput&quot;)</value>
   </webElementProperties>
</WebElementEntity>
