<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>View Full History</name>
   <tag></tag>
   <elementGuidId>f2719ca1-9224-4088-ae16-4c0846db127f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[text() = 'View Full History' or . = 'View Full History']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@id = 'ANCQuotesCommon_wt26_block_wtMainContent_wt123_WebPatterns_wt2_block_wtTitle_wt26' and @href = 'https://qa.leap.schneider-electric.com/ANCQuotes_BO/AuditHistory.aspx?(Not.Licensed.For.Production)=' and (text() = 'View Full History' or . = 'View Full History')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ANCQuotesCommon_wt26_block_wtMainContent_wt123_WebPatterns_wt2_block_wtTitle_wt26</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>171</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://qa.leap.schneider-electric.com/ANCQuotes_BO/AuditHistory.aspx?(Not.Licensed.For.Production)=</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Full History</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ANCQuotesCommon_wt26_block_wtMainContent_wt123_WebPatterns_wt2_block_wtTitle_wt26&quot;)</value>
   </webElementProperties>
</WebElementEntity>
